### ISSUE TITLE
demo.py refers to nonexisting text file

### ISSUE THREAD

**Issue by henricryden** [bretglun/BlochBuster#1]
# Dear Dr.

The demo.py file in this excellent repository is referencing a SE.txt file located under config/, but there is no such file. Can this be solved in some way?

**Comment by bretglun** [comment]
Dear Dr Henricryden,
----------------------
Thank you for pointing out this important issue! Our team has looked into the matter and came up with a sofisticated yet simple solution. You will find it in our latest commit, 4bbdb76.
