### ISSUE TITLE
add azimuth and elecation in config

### ISSUE THREAD

**Issue by j01993** [bretglun/BlochBuster#4]
Hi. Thanks for the wonderful code. I just wanted to let you know that I got errors when just running SE.yml. 

python BlochBuster.py -c "config/SE.yml"
AttributeError: 'NoneType' object has no attribute 'deg2rad'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "BlochBuster.py", line 1392, in <module>
    parseAndRun()
  File "BlochBuster.py", line 1389, in parseAndRun
    run(args.configFile, args.leapFactor)
  File "BlochBuster.py", line 1348, in run
    fig = plotFrame3D(config, vectors, frame, output)
  File "BlochBuster.py", line 154, in plotFrame3D
    projection = np.array([np.cos(np.deg2rad(output['azimuth'])) * np.cos(np.deg2rad(output['elevation'])),
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable deg2rad method

I just added two lines in SE.yml and it works fine
    azimuth: -78
    elevation: 30

**Comment by bretglun** [comment]
Thanks for pointing out! This has been resolved in commit b7cc96a
